# Generated by Django 5.1.4 on 2025-03-30 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Source',
        ),
    ]
